### ISSUE TITLE
Home Screen apps at bottom of screen now shows a blur

### ISSUE THREAD

**Issue by redan21** [UsrLightmann/SortingSwipe#1]
Sorry I’m in a blonde moment rn, and forgot what you call it, but check out the picture I attached. The main apps that I use at the bottom of my phone god why tf can’t I recall what it’s named... anyway, it’s completely blurred out now, and cannot access the apps down there anymore 
![B3A48669-67D3-4B59-972E-321ADC35ED8B](https://user-images.githubusercontent.com/29383104/109581792-cfdb7c00-7ab1-11eb-9126-3a8959fdb01e.png)

**Comment by L1ghtmann** [comment]
Hey! Nothing is blurred out...the apps are removed from the dock upon sorting.
